- name: Create {{ group }} group
  group: name={{ group }} state=present

- name: ensure packages installed
  apt: pkg={{ item }} state=latest
  with_items:
    - make
    - build-essential
    - tcl8.5

- name: download latest stable redis
  get_url: url=http://download.redis.io/redis-stable.tar.gz dest=/tmp/redis-stable.tar.gz

- name: untar redis
  command: tar zxf /tmp/redis-stable.tar.gz -C /tmp

- name: build redis
  command: make -C /tmp/redis-stable

- name: create redis group
  group: name=redis state=present system=yes

- name: create redis user
  user: name=redis group=redis createhome=no shell=/bin/false system=yes state=present

- name: make sure that /etc/redis exists
  file: path=/etc/redis state=directory mode=0755

- name: make sure that /var/db/redis exists
  file: path=/var/db/redis state=directory mode=0755 group=redis owner=redis

- name: make sure redis.log file exists
  copy: src=roles/redis/templates/redis.log dest=/var/log/redis.log owner=redis group=redis mode=0644
  tags:
    - start_redis
    
- name: copy upstart file
  copy: src=roles/redis/templates/upstart.conf dest=/etc/init/redis.conf
  tags:
    - start_redis

- name: copy redis.conf file
  copy: src=roles/redis/templates/redis.conf dest=/etc/redis/redis.conf group=redis owner=redis
  tags:
    - start_redis

- name: copy custom template
  template: src=roles/redis/templates/redis.local.conf.j2 dest=/etc/redis/redis.local.conf group=redis owner=redis
  tags:
    - start_redis

- name: copy redis-local script
  template: src=roles/redis/templates/redis-local.j2 dest=/usr/local/bin/redis-local mode=0755
  tags:
    - start_redis

- name: installing redis binaries
  command: cp -f /tmp/redis-stable/src/{{ item }} /usr/local/bin
  with_items: 
    - redis-server
    - redis-cli
    - redis-check-aof
    - redis-check-dump

- name: cleaning up build files
  command: rm -rf /tmp/{{ item }}
  with_items:
    - redis-stable
    - redis-stable.tar.gz

- name: ensure redis service is restarted
  service: name=redis state=restarted
  tags:
    - start_redis