---
# initial update of OS for reach VM
- hosts: vms
  sudo: true
  roles:
  - {role: common, tags: common}
  handlers:
  - name: restart ssh
    service: name=ssh state=restarted


- hosts: dbservers
  sudo: yes
  roles:
    - {role: pg, tags: pg}
    # - {role: sqlite, tags: sqlite} # really simple applications only
  handlers:  
  - name: restart ssh
    service: name=ssh state=restarted


- hosts: webservers
  sudo: yes
  roles:
    - {role: rbenv, tags: rbenv}
    - {role: node, tags: node}
    - {role: redis, tags: redis}
    # - {role: pg_ssh_tunnel, tags: pg_ssh_tunnel} # uncomment for multi server / horizontal scaling.
    # - {role: elasticsearch, tags: elasticsearch} # uncomment for elasticsearch
    - {role: app_install, tags: app_install}
    # - {role: sidekiq, tags: sidekiq} # uncomment for sidekiq
    - {role: nginx, tags: nginx}
  handlers:
  - name: restart ssh
    service: name=ssh state=restarted


# Must run --tags "nginx_load_balancer" for load balancer config to work
- hosts: loadbalancers
  sudo: yes
  roles:
    # - {role: nginx_load_balancer, tags: nginx_load_balancer} # uncomment for multi server / horizontal scaling
  handlers:
  - name: restart ssh
    service: name=ssh state=restarted    

