# ansible-playbook site.yml
---
# - include: vms.yml
# - include: dbservers.yml
# - include: webservers.yml


# initial update of OS for reach VM
- hosts: vms
  sudo: true
  roles:
  - {role: common, tags: common}
  handlers:
  - name: restart ssh
    service: name=ssh state=restarted


- hosts: dbservers
  sudo: yes
  roles:
    # - {role: pg, tags: pg}
    - {role: sqlite, tags: sqlite}
  handlers:  
  - name: restart ssh
    service: name=ssh state=restarted


- hosts: webservers
  sudo: yes
  roles:
    - {role: rbenv, tags: rbenv}
    - {role: node, tags: node}
    - {role: redis, tags: redis}
    # - {role: elasticsearch, tags: elasticsearch}
    - {role: app_install, tags: app_install}
    # - {role: sidekiq, tags: sidekiq}
  handlers:
  - name: restart ssh
    service: name=ssh state=restarted
    
- hosts: loadbalancers
  sudo: yes
  roles:
    - {role: nginx, tags: nginx}
    # - {role: nginx_load_balance_only, tags: nginx_load_balance_only}
  handlers:
  - name: restart ssh
    service: name=ssh state=restarted    

