- hosts: loadbalancers
  sudo: yes
  roles:
    - {role: nginx, tags: nginx}
  handlers:
  - name: restart ssh
    service: name=ssh state=restarted    

- hosts: webservers
  sudo: yes
  roles:
    - {role: rbenv, tags: rbenv}
    - {role: node, tags: node}
    - {role: redis, tags: redis}
    - {role: elasticsearch, tags: elasticsearch}
    - {role: app, tags: app}
    - {role: sidekiq, tags: sidekiq}
  handlers:
  - name: restart ssh
    service: name=ssh state=restarted
