# RESTART!!!
- name: restart app
  service: name=unicorn_{{appname}} state=restarted enabled=yes sleep=2
  sudo: yes
  tags:
    - unicorn
    - reboot

- name: restart nginx
  service: name=nginx state=reloaded enabled=yes
  sudo: yes
  tags:
    - unicorn
    - reboot

- name: elasticsearch services on boot
  service: name=elasticsearch state=restarted enabled=yes
  sudo: yes
  tags:
    - elasticsearch
    - reboot

- name: ensure app permissions
  file: path=/home/{{user}}/app owner={{user}} group={{group}} mode=0777 recurse=yes
  sudo: yes

- name: restart nginx
  service: name=nginx state=reloaded enabled=yes
  sudo: yes
  tags:
    - unicorn
    - reboot

- name: use remote DB
  shell: bash -lc "ssh -f -N -L 5432:127.0.0.1:5432 deployer@192.168.33.11" #"
  when: migration_change_result|failed
  notify:
    - restart app
  tags:
    - remote_db