# How does UNIX test work? See below for example of expected output.
# ryans-mbp-2:ansibletest ryanmcgary$ node -v
# v0.10.24
# ryans-mbp-2:ansibletest ryanmcgary$ test "$(node -v 2> /dev/null)" = v0.10.24 && echo 1
# 1
# ryans-mbp-2:ansibletest ryanmcgary$ test "$(node -v 2> /dev/null)" = v0.10.21 && echo 1
# ryans-mbp-2:ansibletest ryanmcgary$
# node_version: "0.10.24"
# node_prefix: "node-v0.10.24"
# node_tarball: "node-v0.10.24.tar.gz"
# curl -s -D - http://nodejs.org/dist/v0.10.24/node-v0.10.24.tar.gz -o /dev/null

# - name: copy from each server
#   fetch: src=/home/vagrant/postinstall.sh dest=/Users/ryanmcgary/fetched
- name: Node.js | Checking installed version of node.js
  shell: /usr/bin/test "$(node -v 2> /dev/null)" = "v{{node_version}}" #"
  register: wanted_version_installed
  ignore_errors: True

- name: Node.js | Fetching node.js source
  action: get_url url=http://nodejs.org/dist/v{{ node_version }}/{{ node_tarball }} dest=/tmp/
  when: wanted_version_installed.rc == 1

- name: Node.js | Unpack node.js tarball
  command: tar zxf {{ node_tarball }} chdir=/tmp
  when: wanted_version_installed.rc == 1

- name: Node.js | Configure
  shell: /usr/bin/python ./configure --prefix={{ node_path }} chdir=/tmp/{{ node_prefix }}
  when: wanted_version_installed.rc == 1

- name: Node.js | Make
  shell: /usr/bin/make chdir=/tmp/{{ node_prefix }}/
  when: wanted_version_installed.rc == 1

- name: Node.js | Make install
  shell: /usr/bin/make install chdir=/tmp/{{ node_prefix }}/
  when: wanted_version_installed.rc == 1