# https://github.com/francisbesset/ansible-playbooks/tree/master/nginx
- name: install nginx
  action: apt name=nginx
  tags:
  - nginx

- name: write nginx.conf
  action: template src=../templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx
  tags:
  - nginx

- name: delete default vhost
  action: file path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - restart nginx
  tags:
  - nginx