# RESTART!!!
- name: restart app
  service: name=unicorn_{{appname}} state=restarted enabled=yes sleep=2
  sudo: yes

- name: restart nginx
  service: name=nginx state=reloaded enabled=yes
  sudo: yes

- name: restart sidekiq
  service: name=sidekiq_{{appname}} state=restarted enabled=yes sleep=2
  sudo: yes

- name: restart elasticsearch
  service: name=elasticsearch state=restarted enabled=yes
  sudo: yes

- name: ensure app permissions
  file: path=/home/{{user}}/app owner={{user}} group={{group}} mode=0777 recurse=yes
  sudo: yes

- include: ../../pg/handlers/main.yml
- include: ../../pg_ssh_tunnel/handlers/main.yml  