# RESTART!!!
- name: restart app
  service: name=unicorn_{{appname}} state=restarted enabled=yes sleep=2
  sudo: yes
  tags:
    - unicorn
    - reboot
    - deploy

- name: restart nginx
  service: name=nginx state=reloaded enabled=yes
  sudo: yes
  tags:
    - unicorn
    - reboot  
    - deploy  

- name: restart sidekiq
  service: name=sidekiq_{{appname}} state=restarted enabled=yes sleep=2
  sudo: yes
  tags:
    - reboot
    - deploy

- name: restart elasticsearch
  service: name=elasticsearch state=restarted enabled=yes
  sudo: yes
  tags:
    - elasticsearch
    - reboot    